### ISSUE TITLE
Add giveaway/raffle feature

### ISSUE THREAD

**Issue by otothea** [otothea/botisimo#82]

**Comment by shawnbutts** [comment]
I managed to get something working a streamdeck and it's multi-action feature.  

1. open raffle chat message
2. 5 minute delay
3. reminder chat message
4. 5 minute delay
5. reminder chat message
6. 5 minute delay
7. raffle draw message
8. The raffle winners is $(winner 15 !ticket)!!!!
9. play sound

still trying to figure out a way to get an overlay notification too and a confirmation chat message for when they enter.

something built into botisimo would be much better since it wouldn't rely on something local to me for it to run.

**Comment by shawnbutts** [comment]
this might work in botisimo as well...

A raffle has started!!!  Type !ticket to enter. I will draw in 15 minutes and you must be a follower to win.
$[chain]$[delay 300] 10 minutes to get in on the raffle.  Type !ticket to enter. You must be a follower to win.
$[chain]$[delay 300] 5 minutes to get in on the raffle.  Type !ticket to enter. You must be a follower to win.
$[chain]$[delay 300]Drawing raffle winner...... You must be a follower to win.
$[chain] $[delay 3] The raffle winner is $(winner 16 !ticket)!!!!

still need an overlay solution with sound so i don't have to keep checking chat.

edit:  it kinda works.  but, it always has no winner.  even with i've typed !ticket in chat multiple times.
